### ISSUE TITLE
Klaxon Oncall Pager is no longer available in the Google playstore

### ISSUE THREAD

**Issue by xiconfjs** [muncus/klaxon-wip#4]
Hi @muncus,

just checking if you need help with the Klaxon Oncall Pager development, cause it's no longer available in the Google playstore. 

Thanks
xiconfjs

**Comment by muncus** [comment]
Sorry about that. There's a requirement that apps which requests "sensitive" permissions have a published privacy policy. Klaxon does not currently have one, but i'll put one together as soon as i'm able.

**Comment by xiconfjs** [comment]
@muncus: Thanks. If you need any support, please don't hesitate you contact me.

**Comment by muncus** [comment]
I've published a privacy policy through the play store listing now (hosted here: http://muncus.github.io/klaxon-wip/privacy)

I believe this update is now live, but if you still encounter problems, please reopen this issue and i'll investigate.

Thanks!

**Comment by xiconfjs** [comment]
Thanks, works like a charm.
