### ISSUE TITLE
Klaxon Oncall Pager is no longer available in the Google playstore

### ISSUE THREAD

**Issue by xiconfjs** [muncus/klaxon-wip#5]
Hi @muncus,

the app is again no longer available in the Google Play store. I tried to reopen the old issue #4 but didn't manage to, so there is a new one.

Thanks again
xiconfjs

**Comment by muncus** [comment]
Hi, thanks for bringing this to my attention.
I'm working on getting it back in the play store, but having some trouble trying to test.

Stay tuned on this bug, and i'll have an update for you as soon as i get it sorted out.
Thanks again.

**Comment by xiconfjs** [comment]
If there is any way we can help you with bringing this back into the Play store, feel free to contact me.

**Comment by muncus** [comment]
As you've probably guessed in the last 3 years, I have not been able to get Klaxon back into the Play store.
Changes were made to [Play Store policy about SMS permissions](https://support.google.com/googleplay/android-developer/answer/10208820?hl=en#zippy=%2Cpermitted-uses-of-the-sms-and-call-log-permissions%2Cinvalid-uses%2Calternatives-to-common-uses) that essentially prevent this type of app from operating.

Sorry!
